/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.beanslab.cashretriver.personal;

import co.com.beanslab.cashretriver.modelo.Barrios;
import co.com.beanslab.cashretriver.modelo.Municipios;
import co.com.beanslab.cashretriver.modelo.Roles;
import co.com.beanslab.cashretriver.modelo.controllers.BarriosJpaController;
import co.com.beanslab.cashretriver.modelo.controllers.MunicipiosJpaController;
import co.com.beanslab.cashretriver.modelo.controllers.RolesJpaController;
import java.util.List;
import java.util.Vector;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//co.com.beanslab.cashretriver.personal//PersonalAdmin//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "PersonalAdminTopComponent",
        iconBase = "co/com/beanslab/cashretriver/personal/personal_16x16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "co.com.beanslab.cashretriver.personal.PersonalAdminTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PersonalAdminAction",
        preferredID = "PersonalAdminTopComponent")
@Messages({
    "CTL_PersonalAdminAction=PersonalAdmin",
    "CTL_PersonalAdminTopComponent=PersonalAdmin Window",
    "HINT_PersonalAdminTopComponent=This is a PersonalAdmin window"
})
public final class PersonalAdminTopComponent extends TopComponent {

    public PersonalAdminTopComponent() {
        initComponents();
        setName(Bundle.CTL_PersonalAdminTopComponent());
        setToolTipText(Bundle.HINT_PersonalAdminTopComponent());
        iniciarDatos();
        autocompletado();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rol_jComboBox = new javax.swing.JComboBox();
        nombre_jTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellido_jTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefono_jTextField = new javax.swing.JTextField();
        celular_jTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        direccion_jTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        barrio_jComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        municipio_jComboBox = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.blue)); // NOI18N
        jPanel1.setToolTipText(org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jPanel1.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel1.text")); // NOI18N

        rol_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nombre_jTextField.setText(org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.nombre_jTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel2.text")); // NOI18N

        apellido_jTextField.setText(org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.apellido_jTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel3.text")); // NOI18N

        telefono_jTextField.setText(org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.telefono_jTextField.text")); // NOI18N

        celular_jTextField.setText(org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.celular_jTextField.text")); // NOI18N
        celular_jTextField.setToolTipText(org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.celular_jTextField.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel4.text")); // NOI18N

        direccion_jTextField.setText(org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.direccion_jTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel6.text")); // NOI18N

        barrio_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(PersonalAdminTopComponent.class, "PersonalAdminTopComponent.jLabel8.text")); // NOI18N

        municipio_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_jTextField)
                    .addComponent(telefono_jTextField)
                    .addComponent(celular_jTextField)
                    .addComponent(direccion_jTextField)
                    .addComponent(barrio_jComboBox, 0, 238, Short.MAX_VALUE)
                    .addComponent(rol_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido_jTextField)
                    .addComponent(municipio_jComboBox, 0, 204, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rol_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(apellido_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefono_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(celular_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(direccion_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(barrio_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(municipio_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido_jTextField;
    private javax.swing.JComboBox barrio_jComboBox;
    private javax.swing.JTextField celular_jTextField;
    private javax.swing.JTextField direccion_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox municipio_jComboBox;
    private javax.swing.JTextField nombre_jTextField;
    private javax.swing.JComboBox rol_jComboBox;
    private javax.swing.JTextField telefono_jTextField;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void iniciarDatos() {
     
        llenaRoles();
        llenaBarrios();
        llenaMunicipios();
        
     
    }

    private void llenaRoles() {
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("ModeloPU");
        RolesJpaController rolesJpaController=new RolesJpaController(emf);
        List<Roles> findRolesEntities = rolesJpaController.findRolesEntities();                
        rol_jComboBox.setModel(new DefaultComboBoxModel((Vector<Roles>)findRolesEntities));
        
    }

    private void llenaBarrios() {
       EntityManagerFactory emf=Persistence.createEntityManagerFactory("ModeloPU");
        BarriosJpaController barriosController=new BarriosJpaController(emf);
        List<Barrios> barriosEntities = barriosController.findBarriosEntities();
        barrio_jComboBox.setModel(new DefaultComboBoxModel((Vector<Barrios>)barriosEntities));
    }

    private void llenaMunicipios() {
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("ModeloPU");
        MunicipiosJpaController mjc=new MunicipiosJpaController(emf);
        List<Municipios> municipioses = mjc.findMunicipiosEntities();
        municipio_jComboBox.setModel(new DefaultComboBoxModel((Vector<Municipios>)municipioses));
    }

    private void autocompletado() {
        AutoCompleteDecorator.decorate(rol_jComboBox);
        AutoCompleteDecorator.decorate(barrio_jComboBox);
        AutoCompleteDecorator.decorate(municipio_jComboBox);
    }
}
